export const tableFields = [
    {
      title: "Fecha",
      dataIndex: "date",
      key: "date",
      fixed: "left",
      width: 15,
    },
    {
      title: "Ubicacion",
      dataIndex: "location",
      key: "location",
      width: 15,
    },
    {
      title: "Lote",
      dataIndex: "lote",
      key: "lote",
      width: 10,
    },
    {
      title: "Area Plantada",
      dataIndex: "plantedArea",
      key: "plantedArea",
      width: 15,
    },
    {
      title: "Germinacion",
      dataIndex: "germination",
      key: "germination",
      width: 25,
    },
    {
      title: "Tiempo de Siembra",
      dataIndex: "seedTime",
      key: "seedTime",
      width: 25,
    },
    {
      title: "Altura",
      dataIndex: "heigth",
      key: "heigth",
      width: 25,
    },
    {
      title: "Diametro",
      dataIndex: "diameter",
      key: "diameter",
      width: 25,
    },
    {
      title: "Ramas",
      dataIndex: "bunches",
      key: "bunches",
      width: 25,
    },
    {
      title: "Flores por rama",
      dataIndex: "flowersPerBunch",
      key: "flowersPerBunch",
      width: 25,
    },
    {
      title: "Flores totales",
      dataIndex: "totalFlowers",
      key: "totalFlowers",
      width: 25,
    },
    {
      title: "Frutos por ramas",
      dataIndex: "fruitPerBunch",
      key: "fruitPerBunch",
      width: 50,
    },
    {
      title: "Frutos totales",
      dataIndex: "totalFruit",
      key: "totalFruit",
      width: 50,
    },
    {
      title: "Largo Frutos",
      dataIndex: "fruitLength",
      key: "fruitLength",
      width: 50,
    },
    {
      title: "Diametro de fruto",
      dataIndex: "fruitDiameter",
      key: "fruitDiameter",
      width: 25,
    },
    {
      title: "Peso de fruto",
      dataIndex: "fruitWeigth",
      key: "fruitWeigth",
      width: 25,
    },
    {
      title: "Producción por planta",
      dataIndex: "productionPerPlant",
      key: "productionPerPlant",
      width: 25,
    },
    {
      title: "Ph del suelo",
      dataIndex: "groundPh",
      key: "groundPh",
      width: 25,
    },
    {
      title: "Mo",
      dataIndex: "mo",
      key: "mo",
      width: 25,
    },
    {
      title: "Nitrógeno",
      dataIndex: "nitrogen",
      key: "nitrogen",
      width: 25,
    },
    {
      title: "Fósforo",
      dataIndex: "match",
      key: "match",
      width: 25,
    },
    {
      title: "Potasio",
      dataIndex: "potassium",
      key: "potassium",
      width: 25,
    },
    {
      title: "Otros elementos",
      dataIndex: "otherElements",
      key: "otherElements",
      width: 20,
    },
    {
      title: "Temperatura",
      dataIndex: "temperature",
      key: "temperature",
      width: 20,
    },
    {
      title: "Humedad Relativa",
      dataIndex: "relativeHumidity",
      key: "relativeHumidity",
      width: 20,
    },
    {
      title: "Irrigación / Lluvia",
      dataIndex: "irrigationRain",
      key: "irrigationRain",
      width: 20,
    },
    {
      title: "Fertilizante",
      dataIndex: "fertilizer",
      key: "fertilizer",
      width: 20,
    },
    {
      title: "Fecha de fertilización",
      dataIndex: "fertilizerDate",
      key: "fertilizerDate",
      width: 20,
    },
    {
      title: "Control de plagas",
      dataIndex: "plagueControl",
      key: "plagueControl",
      width: 20,
    },
    {
      title: "Cantidad (Control de plagas)",
      dataIndex: "plagueControlAmount",
      key: "plagueControlAmount",
      width: 20,
    },
    {
      title: "Fecha de control de plagas",
      dataIndex: "plagueControlDate",
      key: "plagueControlDate",
      width: 20,
    },
    {
      title: "Observaciones",
      dataIndex: "observations",
      key: "observations",
      fixed: "right",
      width: 20,
    },
  ];